version: '3'

services:
  redis:
    image: redis:4.0-alpine
    command: redis-server
  
  app:
    build:
      context: .
    image: shehabeldeen/yala-notlob:v1.0.0
    container_name: yalanotlob
    ports:
        - 3000:3000
    stdin_open: true
    tty: true
    command: >
        bash -c "rails db:migrate
        && rm -f tmp/pids/server.pid
        && rails server -p 3000 -b 0.0.0.0"
    depends_on:
        - redis
    environment: 
        - REDIS_URL=redis://redis:6379/1
    links:
        - redis
