development:
  FACEBOOK_APP_ID: "477384463414259"
  FACEBOOK_APP_SECRET: "ea5d33e95b052e38fe1ab1553299ecdc"
  GMAIL_APP_ID: "370432433202-n2viuiovqlhov3en319k98g6shvfkdk6.apps.googleusercontent.com"
  GMAIL_APP_SECRET: "fFfneE1a6iQLDAWWO9P59AYE"